In [10]:
import pandas as pd
from pathlib import Path
import numpy as np
from ase.units import Hartree, mol, kcal
import ast
import os
import sys
os.chdir('../')
sys.path.append('src/pKalculator')
from solvents_parameters import gen_solvent_df
from solvents_parameters import find_all_combinations

### test solvent combinations

In [11]:
dict_iter_xtb = {
            'method' : (1, 2), 
            'solvent_model' : ('gbsa', 'alpb'),
            'solvent_name' : None
           }
df_solvent = gen_solvent_df()
df_iter_xtb = find_all_combinations(iter_dict=dict_iter_xtb, df_solvent=df_solvent)

In [12]:
df_iter_xtb

    method solvent_model  solvent_name
0        1          gbsa         Water
1        1          gbsa          DMSO
2        1          gbsa  Acetonitrile
3        1          gbsa       Acetone
4        1          gbsa        CH2Cl2
5        1          gbsa           THF
6        1          gbsa         Ether
7        1          gbsa       Toluene
8        1          alpb         Water
9        1          alpb          DMSO
10       1          alpb  Acetonitrile
11       1          alpb       Acetone
12       1          alpb        CH2Cl2
13       1          alpb           THF
14       1          alpb         Ether
15       1          alpb       Toluene
16       2          gbsa         Water
17       2          gbsa          DMSO
18       2          gbsa  Acetonitrile
19       2          gbsa       Acetone
20       2          gbsa        CH2Cl2
21       2          gbsa           THF
22       2          gbsa         Ether
23       2          gbsa       Toluene
24       2          alpb         Water
25       2          alpb          DMSO
26       2          alpb  Acetonitrile
27       2          alpb       Acetone
28       2          alpb        CH2Cl2
29       2          alpb           THF
30       2          alpb         Ether
31       2          alpb       Toluene

In [13]:
for idx, row in df_iter_xtb.iterrows():
    method = row['method']
    solvent_model = row['solvent_model']
    solvent_name = row['solvent_name']
    print(method, solvent_model, solvent_name)

1 gbsa Water
1 gbsa DMSO
1 gbsa Acetonitrile
1 gbsa Acetone
1 gbsa CH2Cl2
1 gbsa THF
1 gbsa Ether
1 gbsa Toluene
1 alpb Water
1 alpb DMSO
1 alpb Acetonitrile
1 alpb Acetone
1 alpb CH2Cl2
1 alpb THF
1 alpb Ether
1 alpb Toluene
2 gbsa Water
2 gbsa DMSO
2 gbsa Acetonitrile
2 gbsa Acetone
2 gbsa CH2Cl2
2 gbsa THF
2 gbsa Ether
2 gbsa Toluene
2 alpb Water
2 alpb DMSO
2 alpb Acetonitrile
2 alpb Acetone
2 alpb CH2Cl2
2 alpb THF
2 alpb Ether
2 alpb Toluene

In [2]:
path_data = Path(Path.home()/'pKalculator'/'data')
df_paper_neutral = pd.read_excel(path_data/"data_paper_neutral.ods", engine="odf")
df_paper_anions = pd.read_excel(path_data/"data_paper_anions.ods", engine="odf")

In [3]:
df_paper_neutral.head()

  Neutral       TCG           E  G(gas)=TCG+E  dG(sol)
0      a1  0.043924 -230.103291   -230.059367    -1.85
1      a2  0.039644 -553.091679   -553.052035    -2.85
2      a3  0.081655 -249.565554   -249.483899    -1.64
3      a4  0.123395 -344.221083   -344.097688     0.45
4      a5  0.070336 -265.619103   -265.548767    -5.92

In [8]:
df_paper_anions.head()

  Anions       TCG           E  G(gas)=TCG+E  ΔG(sol)
0   a1-2  0.028610 -229.467144   -229.438534   -64.94
1   a1-3  0.028988 -229.459639   -229.430651   -65.17
2   a2-2  0.025289 -552.466609   -552.441320   -61.59
3   a2-3  0.024738 -552.453263   -552.428525   -62.08
4   a3-2  0.066085 -248.921456   -248.855371   -63.31

In [53]:
df = pd.read_csv('test_calculations.csv')

In [54]:
df.head()

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa_deprot,gfn method,solvent model,solvent name
0,furan,O1C=CC=C1,35.0,35.0,5a,-9593.19,"['furan#-1=2', 'furan#-1=3']","[-9400.57, -9398.74]","[192.62, 194.45]","[35.14, 35.14]",gfn1,gbsa,Water
1,thiophene,S1C=CC=C1,32.5,33.5,5a,-8961.46,"['thiophene#-1=2', 'thiophene#-1=3']","[-8769.8, -8765.46]","[191.66, 196.0]","[35.14, 35.14]",gfn1,gbsa,Water
2,"N,N-dimethyl-1H-pyrrol-1-amine",CN(N1C=CC=C1)C,36.4,38.7,5a,-15320.66,"['N,N-dimethyl-1H-pyrrol-1-amine#-1=4', 'N,N-d...","[-15126.23, -15116.51, -15123.01]","[194.43, 204.15, 197.65]","[35.14, 35.15, 35.14]",gfn1,gbsa,Water
3,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11332.54,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11138.83, -11135.97, -11125.2, -11147.72]","[193.71, 196.57, 207.34, 184.82]","[35.14, 35.14, 35.15, 35.14]",gfn1,gbsa,Water
4,thiazole,S1C=CN=C1,29.4,29.6,5b,-9300.94,"['thiazole#-1=2', 'thiazole#-1=3', 'thiazole#-...","[-9114.86, -9104.9, -9111.07]","[186.08, 196.04, 189.87]","[35.14, 35.14, 35.14]",gfn1,gbsa,Water

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             320 non-null    object
 1   smiles           320 non-null    object
 2   pka_exp          320 non-null    float64
 3   pka_theor        320 non-null    float64
 4   ref              320 non-null    object
 5   E_neutral        320 non-null    float64
 6   lst_name_deprot  320 non-null    object
 7   lst_E            320 non-null    object
 8   lst_E_rel        320 non-null    object
 9   lst_pKa_deprot   320 non-null    object
 10  gfn method       320 non-null    object
 11  solvent model    320 non-null    object
 12  solvent name     320 non-null    object
dtypes: float64(3), object(10)
memory usage: 32.6+ KB

In [96]:
import ast

In [62]:
for idx in df.index[df['name'] == 'furan']:
    print(df.at[idx, 'solvent name'] == 'DMSO')

False
True
False
False
False
False
False
False
False
True
False
False
False
False
False
False
False
True
False
False
False
False
False
False
False
True
False
False
False
False
False
False

In [67]:
idx_ref = df.index[df['name'] == 'furan'][2]
# print(idx_ref)
# print(idx_ref[0])
print(df.at[idx_ref, 'lst_name_deprot'])

idx_deprot = ast.literal_eval(df.at[idx_ref, 'lst_name_deprot']).index('furan#-1=2')
print(idx_deprot)
print(ast.literal_eval(df.at[idx_ref, 'lst_E_rel'])[idx_deprot])

idx_ref = df.index[df['name'] == 'furan']


idx_ref = df.index[df['name'] == 'furan'][1]
idx_deprot = ast.literal_eval(df.at[idx_ref, 'lst_name_deprot']).index('furan#-1=2')
#take the negative as the relative energy is calculated as Furan --> Furan-
E_rel_ref = - ast.literal_eval(df.at[idx_ref, 'lst_E_rel'])[idx_deprot]

idx = 0
lst_E_rel = ast.literal_eval(df.at[idx, 'lst_E_rel'])
print(lst_E_rel)
pKa_ref = 35
temp = 298.15 #K 
gas_constant = 1.987 

lst_pKa = []
for E_rel in lst_E_rel:

    dG_exchange = E_rel_ref + E_rel
    pKa = pKa_ref + (dG_exchange/(gas_constant*temp*np.log(10)/1000))
    lst_pKa.append(pKa)

print(lst_pKa)

['furan#-1=2', 'furan#-1=3']
0
192.6
[192.62, 194.45]
[35.263908957587354, 36.60544615865632]

### Calculate pKA

In [64]:
def calc_pKa_paper(df_neutral=df_paper_neutral, df_anion=df_paper_anions, ref_neutral='a1', ref_anion='a1-1', neutral=None, anion=None,  pKa_ref=35, T=None):
    """
    Het-H + Furan- --> Het- + Furan
    """
    if T == None:
        T = 298.15 #K
    
    gas_constant = 1.987 #kcal/(mol*K) or 8.31441 J/(mol*K) gas constant
    conversion_factor = Hartree * mol/kcal #convert energy from Hartree to kcal/mol
    
    idx_neutral_ref = df_neutral.index[df_neutral['Neutral'] == ref_neutral][0]
    idx_anion_ref = df_anion.index[df_anion['Anions'] == ref_anion][0]

    G_neutral_ref = df_neutral.at[idx_neutral_ref, 'G(gas)=TCG+E'] * conversion_factor + df_neutral.at[idx_neutral_ref, 'dG(sol)']
    G_anion_ref = df_anion.at[idx_anion_ref, 'G(gas)=TCG+E'] * conversion_factor + df_anion.at[idx_anion_ref, 'dG(sol)']

    idx_neutral = df_neutral.index[df_neutral['Neutral'] == neutral][0]
    idx_anion = df_anion.index[df_anion['Anions'] == anion][0]

    G_neutral = df_neutral.at[idx_neutral, 'G(gas)=TCG+E'] * conversion_factor + df_neutral.at[idx_neutral, 'dG(sol)']
    G_anion = df_anion.at[idx_anion, 'G(gas)=TCG+E'] * conversion_factor + df_anion.at[idx_anion, 'dG(sol)']
    
    dG_exchange = G_neutral_ref + G_anion - G_anion_ref - G_neutral

    pKa = pKa_ref + (dG_exchange/(gas_constant*T*np.log(10)/1000))

    return round(pKa, 1)

In [58]:
def get_pKa_from_entry(df_neutral=df_paper_neutral, df_anion=df_paper_anions, neutral=''):
    """
    Returns a tuple of anions and the pKa values calculated from the common neutral compound
    """
    idx_anions = df_anion.index[df_anion['Anions'].str.contains(neutral+'-', regex=False)].tolist()
    
    pKas = [calc_pKa_paper(df_neutral=df_paper_neutral, df_anion=df_paper_anions, ref_neutral='a1', ref_anion='a1-2', neutral=neutral, anion=df_anion.Anions[idx],  pKa_ref=35, T=None) for idx in idx_anions]
    anion_names = [df_anion.Anions[idx]for idx in idx_anions]
    tup_names_pKas =tuple(zip(anion_names, pKas))

    return tup_names_pKas

In [59]:
get_pKa_from_entry(neutral='a1')

(('a1-2', 35.0), ('a1-3', 38.46))

In [77]:
import itertools
output_data = list(itertools.chain(*[get_pKa_from_entry(neutral=name) for name in df_paper_neutral.Neutral]))

In [78]:
output_data[:3]

[('a1-2', 35.0), ('a1-3', 38.5), ('a2-2', 33.5)]

In [81]:
pd.DataFrame(output_data, columns=['name_paper', 'pKa_paper'])

    name_paper  pKa_paper
0         a1-2       35.0
1         a1-3       38.5
2         a2-2       33.5
3         a2-3       39.1
4         a3-2       39.6
..         ...        ...
186       d7-8       40.0
187       d8-2       36.1
188       d8-4       33.5
189       d8-6       34.6
190       d8-7       34.4

[191 rows x 2 columns]

In [75]:
list(zip(*output_data))

[(('a1-2', 35.0),
  ('a2-2', 33.5),
  ('a3-2', 39.6),
  ('a4-2', 38.8),
  ('a5-2', 35.2),
  ('a6-2', 29.5),
  ('a7-2', 27.1),
  ('a8-3', 39.6),
  ('a9-3', 40.5),
  ('a10-3', 32.7),
  ('a11-3', 31.9),
  ('a12-3', 35.8),
  ('a13-2', 35.4),
  ('a14-3', 38.3),
  ('a15-2', 32.2),
  ('b1-1', 44.7),
  ('b2-2', 43.6),
  ('b3-3', 37.9),
  ('b4-2', 40.0),
  ('b5-2', 39.4),
  ('b6-1', 34.9),
  ('b7-4', 33.0),
  ('b8-3', 34.4),
  ('b9-2', 36.8),
  ('b10-2', 38.2),
  ('b11-2', 36.2),
  ('b12-2', 44.3),
  ('b13-2', 39.7),
  ('b14-4', 41.7),
  ('b15-2', 28.7),
  ('b16-2', 40.1),
  ('b17-6', 29.0),
  ('b18-4', 33.2),
  ('b19-3', 26.1),
  ('b20-2', 27.6),
  ('b21-5', 30.6),
  ('b22-4', 25.0),
  ('b23-3', 23.1),
  ('c1-2', 37.7),
  ('c2-1', 37.7),
  ('c3-2', 32.0),
  ('c4-1', 31.8),
  ('c5-2', 33.3),
  ('c6-1', 33.1),
  ('c7-1', 42.0),
  ('c8-2', 40.3),
  ('c9-2', 24.8),
  ('c10-2', 27.3),
  ('c11-2', 32.5),
  ('c12-3', 36.3),
  ('c13-3', 32.7),
  ('c14-3', 28.1),
  ('d1-1', 43.4),
  ('d2-2', 42.4),
  ('d3-1', 41.6),
  ('d4-2', 38.5),
  ('d5-3', 39.0),
  ('d6-1', 36.1),
  ('d7-2', 39.7),
  ('d8-2', 36.1))]

[('a1-2', 35.0),
 ('a1-3', 38.5),
 ('a2-2', 33.5),
 ('a2-3', 39.1),
 ('a3-2', 39.6),
 ('a3-3', 44.7),
 ('a4-2', 38.8),
 ('a4-3', 43.5),
 ('a5-2', 35.2),
 ('a5-4', 42.3),
 ('a5-5', 35.1),
 ('a6-2', 29.5),
 ('a6-4', 36.8),
 ('a6-5', 29.6),
 ('a7-2', 27.1),
 ('a7-4', 36.4),
 ('a7-5', 30.6),
 ('a8-3', 39.6),
 ('a8-4', 40.7),
 ('a8-5', 34.9),
 ('a9-3', 40.5),
 ('a9-4', 40.7),
 ('a9-5', 35.2),
 ('a10-3', 32.7),
 ('a10-4', 35.8),
 ('a10-5', 28.1),
 ('a11-3', 31.9),
 ('a11-4', 34.0),
 ('a11-5', 27.7),
 ('a12-3', 35.8),
 ('a12-5', 30.4),
 ('a13-2', 35.4),
 ('a13-3', 40.4),
 ('a14-3', 38.3),
 ('a14-4', 37.2),
 ('a14-5', 32.2),
 ('a15-2', 32.2),
 ('a15-4', 38.8),
 ('a15-5', 32.6),
 ('b1-1', 44.7),
 ('b2-2', 43.6),
 ('b2-3', 41.0),
 ('b2-4', 40.3),
 ('b3-3', 37.9),
 ('b3-4', 35.8),
 ('b4-2', 40.0),
 ('b4-4', 38.9),
 ('b4-5', 36.9),
 ('b5-2', 39.4),
 ('b6-1', 34.9),
 ('b7-4', 33.0),
 ('b7-5', 31.1),
 ('b8-3', 34.4),
 ('b8-5', 33.5),
 ('b8-6', 33.1),
 ('b9-2', 36.8),
 ('b9-3', 42.3),
 ('b9-4', 43.7),
 ('b10-2', 38.2),
 ('b10-3', 40.5),
 ('b10-4', 40.9),
 ('b11-2', 36.2),
 ('b11-3', 39.9),
 ('b11-4', 40.1),
 ('b12-2', 44.3),
 ('b12-3', 43.3),
 ('b12-4', 44.2),
 ('b13-2', 39.7),
 ('b13-3', 41.7),
 ('b13-4', 41.9),
 ('b14-4', 41.7),
 ('b14-6', 33.9),
 ('b15-2', 28.7),
 ('b15-4', 35.8),
 ('b15-5', 39.9),
 ('b16-2', 40.1),
 ('b17-6', 29.0),
 ('b18-4', 33.2),
 ('b18-5', 39.4),
 ('b19-3', 26.1),
 ('b19-5', 33.8),
 ('b19-6', 31.5),
 ('b20-2', 27.6),
 ('b21-5', 30.6),
 ('b22-4', 25.0),
 ('b23-3', 23.1),
 ('c1-2', 37.7),
 ('c1-3', 41.4),
 ('c1-4', 44.8),
 ('c1-5', 46.5),
 ('c1-6', 46.3),
 ('c1-7', 42.1),
 ('c2-1', 37.7),
 ('c2-4', 44.7),
 ('c2-5', 47.1),
 ('c3-2', 32.0),
 ('c3-3', 36.8),
 ('c3-4', 43.0),
 ('c3-5', 44.7),
 ('c3-6', 43.8),
 ('c3-7', 40.3),
 ('c4-1', 31.8),
 ('c4-4', 43.4),
 ('c4-5', 45.1),
 ('c5-2', 33.3),
 ('c5-3', 36.0),
 ('c5-4', 42.6),
 ('c5-5', 44.7),
 ('c5-6', 43.7),
 ('c5-7', 38.1),
 ('c6-1', 33.1),
 ('c6-4', 42.1),
 ('c6-5', 44.8),
 ('c7-1', 42.0),
 ('c7-2', 41.5),
 ('c7-3', 37.0),
 ('c7-5', 36.2),
 ('c7-6', 41.5),
 ('c7-7', 43.4),
 ('c7-8', 40.7),
 ('c8-2', 40.3),
 ('c8-6', 37.3),
 ('c8-8', 29.3),
 ('c9-2', 24.8),
 ('c9-4', 36.2),
 ('c9-5', 42.4),
 ('c9-6', 43.2),
 ('c9-7', 39.7),
 ('c10-2', 27.3),
 ('c10-4', 38.9),
 ('c10-5', 42.6),
 ('c10-6', 43.3),
 ('c10-7', 40.6),
 ('c11-2', 32.5),
 ('c11-4', 42.1),
 ('c11-5', 44.8),
 ('c11-6', 44.6),
 ('c11-7', 40.0),
 ('c12-3', 36.3),
 ('c12-4', 42.4),
 ('c12-5', 45.1),
 ('c12-6', 44.3),
 ('c12-7', 40.2),
 ('c13-3', 32.7),
 ('c13-4', 40.5),
 ('c13-5', 43.3),
 ('c13-6', 42.3),
 ('c13-7', 38.9),
 ('c14-3', 28.1),
 ('c14-4', 39.5),
 ('c14-5', 42.8),
 ('c14-6', 41.4),
 ('c14-7', 36.3),
 ('d1-1', 43.4),
 ('d1-2', 43.8),
 ('d2-2', 42.4),
 ('d2-3', 40.5),
 ('d2-4', 39.2),
 ('d2-5', 41.6),
 ('d2-6', 42.6),
 ('d2-7', 42.3),
 ('d2-8', 42.3),
 ('d3-1', 41.6),
 ('d3-3', 43.6),
 ('d3-4', 40.0),
 ('d3-5', 41.5),
 ('d3-6', 42.1),
 ('d3-7', 42.3),
 ('d3-8', 41.2),
 ('d4-2', 38.5),
 ('d4-5', 40.1),
 ('d4-6', 40.7),
 ('d5-3', 39.0),
 ('d5-4', 35.0),
 ('d5-5', 39.1),
 ('d5-6', 40.3),
 ('d5-7', 40.0),
 ('d5-8', 39.6),
 ('d6-1', 36.1),
 ('d6-5', 38.8),
 ('d6-6', 40.2),
 ('d7-2', 39.7),
 ('d7-4', 37.3),
 ('d7-5', 39.1),
 ('d7-6', 40.9),
 ('d7-7', 40.3),
 ('d7-8', 40.0),
 ('d8-2', 36.1),
 ('d8-4', 33.5),
 ('d8-6', 34.6),
 ('d8-7', 34.4)]

[4, 5]

In [ ]:
df.at[idx, 'solvent_name'] = params['solvent_name']

In [ ]:
df.index[df['name'] == 'furan']

In [11]:
df.sort_values(by=['name', 'solvent name', 'lst_name_deprot'])[:20]

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa_deprot,gfn method,solvent model,solvent name
33,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11335.28,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11136.09, -11133.05, -11122.01, -11146.9]","[199.19, 202.23, 213.27, 188.38]","[35.15, 35.15, 35.16, 35.14]",gfn1,gbsa,Acetone
113,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.00,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11129.43, -11126.36, -11114.68, -11140.37]","[204.57, 207.64, 219.32, 193.63]","[35.15, 35.15, 35.16, 35.14]",gfn1,alpb,Acetone
193,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.71,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10764.75, -10763.23, -10750.41, -10779.83]","[203.96, 205.48, 218.3, 188.88]","[35.15, 35.15, 35.16, 35.14]",gfn2,gbsa,Acetone
273,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10969.19,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10766.05, -10764.94, -10751.81, -10780.04]","[203.14, 204.25, 217.38, 189.15]","[35.15, 35.15, 35.16, 35.14]",gfn2,alpb,Acetone
23,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.25,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11136.23, -11133.18, -11122.47, -11147.31]","[198.02, 201.07, 211.78, 186.94]","[35.15, 35.15, 35.16, 35.14]",gfn1,gbsa,Acetonitrile
103,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.15,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11133.08, -11130.19, -11118.77, -11143.74]","[201.07, 203.96, 215.38, 190.41]","[35.15, 35.15, 35.16, 35.14]",gfn1,alpb,Acetonitrile
183,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.71,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10767.24, -10766.48, -10753.4, -10781.65]","[201.47, 202.23, 215.31, 187.06]","[35.15, 35.15, 35.16, 35.14]",gfn2,gbsa,Acetonitrile
263,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.58,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10767.15, -10766.05, -10753.03, -10781.02]","[201.43, 202.53, 215.55, 187.56]","[35.15, 35.15, 35.16, 35.14]",gfn2,alpb,Acetonitrile
43,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.68,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11131.78, -11128.64, -11117.59, -11142.92]","[202.9, 206.04, 217.09, 191.76]","[35.15, 35.15, 35.16, 35.14]",gfn1,gbsa,CH2Cl2
123,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11335.36,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11134.1, -11131.25, -11119.53, -11144.42]","[201.26, 204.11, 215.83, 190.94]","[35.15, 35.15, 35.16, 35.14]",gfn1,alpb,CH2Cl2
203,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10969.01,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10765.92, -10764.49, -10751.69, -10779.85]","[203.09, 204.52, 217.32, 189.16]","[35.15, 35.15, 35.16, 35.14]",gfn2,gbsa,CH2Cl2
283,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.96,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10766.23, -10765.17, -10752.05, -10779.89]","[202.73, 203.79, 216.91, 189.07]","[35.15, 35.15, 35.16, 35.14]",gfn2,alpb,CH2Cl2
13,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.29,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11136.57, -11133.53, -11122.86, -11147.62]","[197.72, 200.76, 211.43, 186.67]","[35.14, 35.15, 35.15, 35.14]",gfn1,gbsa,DMSO
93,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.43,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11133.43, -11130.73, -11119.19, -11143.79]","[201.0, 203.7, 215.24, 190.64]","[35.15, 35.15, 35.16, 35.14]",gfn1,alpb,DMSO
173,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.29,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10765.67, -10764.74, -10751.65, -10780.57]","[202.62, 203.55, 216.64, 187.72]","[35.15, 35.15, 35.16, 35.14]",gfn2,gbsa,DMSO
253,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10969.03,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10767.95, -10766.74, -10753.72, -10781.66]","[201.08, 202.29, 215.31, 187.37]","[35.15, 35.15, 35.16, 35.14]",gfn2,alpb,DMSO
63,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11334.30,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11128.94, -11125.57, -11114.39, -11140.52]","[205.36, 208.73, 219.91, 193.78]","[35.15, 35.15, 35.16, 35.14]",gfn1,gbsa,Ether
143,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-11333.02,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-11122.97, -11120.01, -11108.06, -11134.59]","[210.05, 213.01, 224.96, 198.43]","[35.15, 35.16, 35.16, 35.15]",gfn1,alpb,Ether
223,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.65,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10761.4, -10760.03, -10747.18, -10775.31]","[207.25, 208.62, 221.47, 193.34]","[35.15, 35.15, 35.16, 35.14]",gfn2,gbsa,Ether
303,1-methyl-1H-imidazole,CN1C=CN=C1,33.1,35.1,5a,-10968.86,"['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...","[-10764.88, -10764.36, -10751.01, -10777.36]","[203.98, 204.5, 217.85, 191.5]","[35.15, 35.15, 35.16, 35.14]",gfn2,alpb,Ether

In [26]:
pd.set_option('display.max_columns', 20, 'display.width', 3000, 'display.max_rows',40)

In [27]:
df[df['solvent name'] == 'DMSO'].sort_values('lst_name_deprot')

                               name                smiles  pka_exp  pka_theor ref  E_neutral                                    lst_name_deprot                                              lst_E                                          lst_E_rel                                     lst_pKa_deprot gfn method solvent model solvent name
13            1-methyl-1H-imidazole            CN1C=CN=C1     33.1       35.1  5a  -11334.29  ['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...       [-11136.57, -11133.53, -11122.86, -11147.62]                   [197.72, 200.76, 211.43, 186.67]                       [35.14, 35.15, 35.15, 35.14]       gfn1          gbsa         DMSO
253           1-methyl-1H-imidazole            CN1C=CN=C1     33.1       35.1  5a  -10969.03  ['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...       [-10767.95, -10766.74, -10753.72, -10781.66]                   [201.08, 202.29, 215.31, 187.37]                       [35.15, 35.15, 35.16, 35.14]       gfn2          alpb         DMSO
173           1-methyl-1H-imidazole            CN1C=CN=C1     33.1       35.1  5a  -10968.29  ['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...       [-10765.67, -10764.74, -10751.65, -10780.57]                   [202.62, 203.55, 216.64, 187.72]                       [35.15, 35.15, 35.16, 35.14]       gfn2          gbsa         DMSO
93            1-methyl-1H-imidazole            CN1C=CN=C1     33.1       35.1  5a  -11334.43  ['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-im...       [-11133.43, -11130.73, -11119.19, -11143.79]                     [201.0, 203.7, 215.24, 190.64]                       [35.15, 35.15, 35.16, 35.14]       gfn1          alpb         DMSO
176              1-methyl-1H-indole  CN(C=C1)C2=C1C=CC=C2     37.3       37.7  5a  -16817.13  ['1-methyl-1H-indole#-1=3', '1-methyl-1H-indol...  [-16613.47, -16600.78, -16599.83, -16597.89, -...  [203.66, 216.35, 217.3, 219.24, 217.32, 212.12...  [35.15, 35.16, 35.16, 35.16, 35.16, 35.16, 35.14]       gfn2          gbsa         DMSO
256              1-methyl-1H-indole  CN(C=C1)C2=C1C=CC=C2     37.3       37.7  5a  -16817.59  ['1-methyl-1H-indole#-1=3', '1-methyl-1H-indol...  [-16614.1, -16601.67, -16599.83, -16597.84, -1...  [203.49, 215.92, 217.76, 219.75, 217.8, 212.23...  [35.15, 35.16, 35.16, 35.16, 35.16, 35.16, 35.14]       gfn2          alpb         DMSO
16               1-methyl-1H-indole  CN(C=C1)C2=C1C=CC=C2     37.3       37.7  5a  -16986.80  ['1-methyl-1H-indole#-1=3', '1-methyl-1H-indol...  [-16794.6, -16787.69, -16786.43, -16785.61, -1...  [192.2, 199.11, 200.37, 201.19, 200.19, 195.04...  [35.14, 35.15, 35.15, 35.15, 35.15, 35.14, 35.14]       gfn1          gbsa         DMSO
96               1-methyl-1H-indole  CN(C=C1)C2=C1C=CC=C2     37.3       37.7  5a  -16987.22  ['1-methyl-1H-indole#-1=3', '1-methyl-1H-indol...  [-16789.76, -16781.48, -16779.45, -16778.63, -...  [197.46, 205.74, 207.77, 208.59, 207.58, 201.5...  [35.14, 35.15, 35.15, 35.15, 35.15, 35.15, 35.14]       gfn1          alpb         DMSO
175            1-propyl-1H-pyrazole          CCCN1N=CC=C1     35.2       35.2  5a  -14931.69  ['1-propyl-1H-pyrazole#-1=8', '1-propyl-1H-pyr...  [-14731.11, -14717.52, -14714.99, -14739.8, -1...    [200.58, 214.17, 216.7, 191.89, 210.38, 212.89]         [35.15, 35.16, 35.16, 35.14, 35.15, 35.16]       gfn2          gbsa         DMSO
15             1-propyl-1H-pyrazole          CCCN1N=CC=C1     35.2       35.2  5a  -15341.37  ['1-propyl-1H-pyrazole#-1=8', '1-propyl-1H-pyr...  [-15146.67, -15136.98, -15129.35, -15157.51, -...     [194.7, 204.39, 212.02, 183.86, 199.31, 201.2]         [35.14, 35.15, 35.16, 35.13, 35.15, 35.15]       gfn1          gbsa         DMSO
255            1-propyl-1H-pyrazole          CCCN1N=CC=C1     35.2       35.2  5a  -14932.61  ['1-propyl-1H-pyrazole#-1=8', '1-propyl-1H-pyr...  [-14733.6, -14720.02, -14717.16, -14742.0, -14...   [199.01, 212.59, 215.45, 190.61, 209.58, 213.08]         [35.15, 35.16, 35.16, 35.14, 35.15, 35.16]       gfn2          alpb         DMSO
95             1-propyl-1H-pyrazole          CCCN1N=CC=C1     35.2       35.2  5a  -15343.25  ['1-propyl-1H-pyrazole#-1=8', '1-propyl-1H-pyr...  [-15147.17, -15136.64, -15129.87, -15157.87, -...   [196.08, 206.61, 213.38, 185.38, 203.96, 207.27]         [35.14, 35.15, 35.16, 35.14, 35.15, 35.15]       gfn1          alpb         DMSO
252  N,N-dimethyl-1H-pyrrol-1-amine        CN(N1C=CC=C1)C     36.4       38.7  5a  -14917.31  ['N,N-dimethyl-1H-pyrrol-1-amine#-1=4', 'N,N-d...                   [-14707.66, -14695.48, -14707.0]                           [209.65, 221.83, 210.31]                              [35.15, 35.16, 35.15]       gfn2          alpb         DMSO
172  N,N-dimethyl-1H-pyrrol-1-amine        CN(N1C=CC=C1)C     36.4       38.7  5a  -14916.73  ['N,N-dimethyl-1H-pyrrol-1-amine#-1=4', 'N,N-d...                  [-14705.17, -14693.21, -14711.64]                           [211.56, 223.52, 205.09]                              [35.16, 35.16, 35.15]       gfn2          gbsa         DMSO
12   N,N-dimethyl-1H-pyrrol-1-amine        CN(N1C=CC=C1)C     36.4       38.7  5a  -15322.29  ['N,N-dimethyl-1H-pyrrol-1-amine#-1=4', 'N,N-d...                   [-15121.8, -15112.71, -15120.03]                           [200.49, 209.58, 202.26]                              [35.15, 35.15, 35.15]       gfn1          gbsa         DMSO
92   N,N-dimethyl-1H-pyrrol-1-amine        CN(N1C=CC=C1)C     36.4       38.7  5a  -15324.22  ['N,N-dimethyl-1H-pyrrol-1-amine#-1=4', 'N,N-d...                  [-15122.61, -15111.16, -15120.02]                            [201.61, 213.06, 204.2]                              [35.15, 35.16, 35.15]       gfn1          alpb         DMSO
177               benzo[b]thiophene   C1(SC=C2)=C2C=CC=C1     32.9       32.0  5a  -14702.92  ['benzo[b]thiophene#-1=3', 'benzo[b]thiophene#...  [-14517.29, -14499.45, -14496.79, -14500.48, -...  [185.63, 203.47, 206.13, 202.44, 202.02, 74702...         [35.14, 35.15, 35.15, 35.15, 35.15, 89.76]       gfn2          gbsa         DMSO
17                benzo[b]thiophene   C1(SC=C2)=C2C=CC=C1     32.9       32.0  5a  -14958.06  ['benzo[b]thiophene#-1=3', 'benzo[b]thiophene#...  [-14771.23, -14761.94, -14760.86, -14764.37, -...    [186.83, 196.12, 197.2, 193.69, 196.11, 190.32]         [35.14, 35.14, 35.14, 35.14, 35.14, 35.14]       gfn1          gbsa         DMSO
97                benzo[b]thiophene   C1(SC=C2)=C2C=CC=C1     32.9       32.0  5a  -14958.63  ['benzo[b]thiophene#-1=3', 'benzo[b]thiophene#...  [-14766.11, -14756.26, -14755.11, -14758.67, -...   [192.52, 202.37, 203.52, 199.96, 202.29, 196.34]         [35.14, 35.15, 35.15, 35.15, 35.15, 35.14]       gfn1          alpb         DMSO
257               benzo[b]thiophene   C1(SC=C2)=C2C=CC=C1     32.9       32.0  5a  -14703.19  ['benzo[b]thiophene#-1=3', 'benzo[b]thiophene#...  [-14515.86, -14498.51, -14495.89, -14499.53, -...  [187.33, 204.68, 207.3, 203.66, 203.26, 74703.19]         [35.14, 35.15, 35.15, 35.15, 35.15, 89.76]       gfn2          alpb         DMSO
179                 benzo[d]oxazole   C1(OC=N2)=C2C=CC=C1     24.4       24.8  5b  -15396.77  ['benzo[d]oxazole#-1=8', 'benzo[d]oxazole#-1=7...  [-15195.65, -15193.4, -15199.82, -15195.57, -1...            [201.12, 203.37, 196.95, 201.2, 179.83]                [35.15, 35.15, 35.14, 35.15, 35.13]       gfn2          gbsa         DMSO
99                  benzo[d]oxazole   C1(OC=N2)=C2C=CC=C1     24.4       24.8  5b  -15927.53  ['benzo[d]oxazole#-1=8', 'benzo[d]oxazole#-1=7...  [-15729.97, -15728.98, -15735.2, -15732.11, -1...           [197.56, 198.55, 192.33, 195.42, 184.28]                [35.14, 35.15, 35.14, 35.14, 35.14]       gfn1          alpb         DMSO
259                 benzo[d]oxazole   C1(OC=N2)=C2C=CC=C1     24.4       24.8  5b  -15397.63  ['benzo[d]oxazole#-1=8', 'benzo[d]oxazole#-1=7...  [-15195.78, -15193.55, -15199.88, -15195.87, -...            [201.85, 204.08, 197.75, 201.76, 181.1]                [35.15, 35.15, 35.14, 35.15, 35.13]       gfn2          alpb         DMSO
19                  benzo[d]oxazole   C1(OC=N2)=C2C=CC=C1     24.4       24.8  5b  -15926.31  ['benzo[d]oxazole#-1=8', 'benzo[d]oxazole#-1=7...  [-15734.66, -15733.84, -15740.21, -15736.79, -...            [191.65, 192.47, 186.1, 189.52, 178.24]                [35.14, 35.14, 35.14, 35.14, 35.13]       gfn1          gbsa         DMSO
18                       benzofuran   C1(OC=C2)=C2C=CC=C1     32.7       33.2  5b  -15587.12  ['benzofuran#-1=3', 'benzofuran#-1=8', 'benzof...  [-15402.27, -15392.79, -15391.62, -15397.97, -...    [184.85, 194.33, 195.5, 189.15, 194.25, 188.05]         [35.14, 35.14, 35.14, 35.14, 35.14, 35.14]       gfn1          gbsa         DMSO
258                      benzofuran   C1(OC=C2)=C2C=CC=C1     32.7       33.2  5b  -15220.33  ['benzofuran#-1=3', 'benzofuran#-1=8', 'benzof...  [-15028.41, -15011.77, -15009.82, -15015.17, -...    [191.92, 208.56, 210.51, 205.16, 207.9, 201.76]         [35.14, 35.15, 35.15, 35.15, 35.15, 35.15]       gfn2          alpb         DMSO
98                       benzofuran   C1(OC=C2)=C2C=CC=C1     32.7       33.2  5b  -15588.40  ['benzofuran#-1=3', 'benzofuran#-1=8', 'benzof...  [-15397.41, -15387.71, -15386.58, -15392.53, -...   [190.99, 200.69, 201.82, 195.87, 200.39, 194.33]         [35.14, 35.15, 35.15, 35.14, 35.15, 35.14]       gfn1          alpb         DMSO
178                      benzofuran   C1(OC=C2)=C2C=CC=C1     32.7       33.2  5b  -15219.57  ['benzofuran#-1=3', 'benzofuran#-1=8', 'benzof...  [-15029.15, -15011.98, -15010.0, -15015.45, -1...   [190.42, 207.59, 209.57, 204.12, 206.97, 200.62]         [35.14, 35.15, 35.15, 35.15, 35.15, 35.15]       gfn2          gbsa         DMSO
170                           furan             O1C=CC=C1     35.0       35.0  5a   -9192.89                       ['furan#-1=2', 'furan#-1=3']                               [-8997.06, -8987.06]                                   [195.83, 205.83]                                     [35.14, 35.15]       gfn2          gbsa         DMSO
90                            furan             O1C=CC=C1     35.0       35.0  5a   -9595.82                       ['furan#-1=2', 'furan#-1=3']                               [-9395.79, -9393.18]                                   [200.03, 202.64]                                     [35.15, 35.15]       gfn1          alpb         DMSO
10                            furan             O1C=CC=C1     35.0       35.0  5a   -9594.89                       ['furan#-1=2', 'furan#-1=3']                                [-9402.63, -9399.9]                                   [192.26, 194.99]                                     [35.14, 35.14]       gfn1          gbsa         DMSO
250                           furan             O1C=CC=C1     35.0       35.0  5a   -9193.63                       ['furan#-1=2', 'furan#-1=3']                               [-8995.83, -8986.32]                                    [197.8, 207.31]                                     [35.15, 35.15]       gfn2          alpb         DMSO
94                         thiazole             S1C=CN=C1     29.4       29.6  5b   -9303.62  ['thiazole#-1=2', 'thiazole#-1=3', 'thiazole#-...                      [-9110.0, -9100.34, -9106.26]                           [193.62, 203.28, 197.36]                              [35.14, 35.15, 35.14]       gfn1          alpb         DMSO
254                        thiazole             S1C=CN=C1     29.4       29.6  5b   -8851.79  ['thiazole#-1=2', 'thiazole#-1=3', 'thiazole#-...                     [-8670.44, -8663.12, -8672.16]                           [181.35, 188.67, 179.63]                              [35.13, 35.14, 35.13]       gfn2          alpb         DMSO
174                        thiazole             S1C=CN=C1     29.4       29.6  5b   -8851.41  ['thiazole#-1=2', 'thiazole#-1=3', 'thiazole#-...                     [-8671.04, -8663.98, -8673.21]                            [180.37, 187.43, 178.2]                              [35.13, 35.14, 35.13]       gfn2          gbsa         DMSO
14                         thiazole             S1C=CN=C1     29.4       29.6  5b   -9303.68  ['thiazole#-1=2', 'thiazole#-1=3', 'thiazole#-...                     [-9116.07, -9106.36, -9112.49]                           [187.61, 197.32, 191.19]                              [35.14, 35.14, 35.14]       gfn1          gbsa         DMSO
171                       thiophene             S1C=CC=C1     32.5       33.5  5a   -8675.01               ['thiophene#-1=2', 'thiophene#-1=3']                               [-8485.92, -8480.66]                                   [189.09, 194.35]                                     [35.14, 35.14]       gfn2          gbsa         DMSO
91                        thiophene             S1C=CC=C1     32.5       33.5  5a   -8964.81               ['thiophene#-1=2', 'thiophene#-1=3']                                [-8765.1, -8760.67]                                   [199.71, 204.14]                                     [35.15, 35.15]       gfn1          alpb         DMSO
11                        thiophene             S1C=CC=C1     32.5       33.5  5a   -8964.33               ['thiophene#-1=2', 'thiophene#-1=3']                               [-8771.58, -8767.34]                                   [192.75, 196.99]                                     [35.14, 35.14]       gfn1          gbsa         DMSO
251                       thiophene             S1C=CC=C1     32.5       33.5  5a   -8675.29               ['thiophene#-1=2', 'thiophene#-1=3']                               [-8484.16, -8479.07]                                   [191.13, 196.22]                                     [35.14, 35.14]       gfn2          alpb         DMSO

In [27]:
print(df['lst_name_deprot'].loc[df.index[13]])

['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-imidazole#-1=6', '1-methyl-1H-imidazole#-1=4', '1-methyl-1H-imidazole#-1=1']

In [30]:
print(df['lst_name_deprot'].loc[df.index[253]])

['1-methyl-1H-imidazole#-1=3', '1-methyl-1H-imidazole#-1=6', '1-methyl-1H-imidazole#-1=4', '1-methyl-1H-imidazole#-1=1']

In [21]:
df.loc[df['name'] == 'furan'].sort_values('solvent name')[12:16]
#[df['solvent name'] == 'DMSO'].sort_values('lst_name_deprot')

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa_deprot,gfn method,solvent model,solvent name
170,furan,O1C=CC=C1,35.0,35.0,5a,-9192.89,"['furan#-1=2', 'furan#-1=3']","[-8997.06, -8987.06]","[195.83, 205.83]","[35.14, 35.15]",gfn2,gbsa,DMSO
250,furan,O1C=CC=C1,35.0,35.0,5a,-9193.63,"['furan#-1=2', 'furan#-1=3']","[-8995.83, -8986.32]","[197.8, 207.31]","[35.15, 35.15]",gfn2,alpb,DMSO
90,furan,O1C=CC=C1,35.0,35.0,5a,-9595.82,"['furan#-1=2', 'furan#-1=3']","[-9395.79, -9393.18]","[200.03, 202.64]","[35.15, 35.15]",gfn1,alpb,DMSO
10,furan,O1C=CC=C1,35.0,35.0,5a,-9594.89,"['furan#-1=2', 'furan#-1=3']","[-9402.63, -9399.9]","[192.26, 194.99]","[35.14, 35.14]",gfn1,gbsa,DMSO

In [2]:
params = {
        'input_smiles' : 'smiles',
        'name' : 'name', 
        'rxn_type' : 'rm_proton'
        }

In [3]:
xtb_params = {
        'method' : 2, 
        'solvent_model' : 'alpb',
        'solvent_name' : 'DMSO'
        }

In [4]:
params.update(xtb_params)

In [5]:
params

{'input_smiles': 'smiles',
 'name': 'name',
 'rxn_type': 'rm_proton',
 'method': 2,
 'solvent_model': 'alpb',
 'solvent_name': 'DMSO'}

In [12]:
def something(args):
    input_smiles, name, rxn_type, method, solvent_model, solvent_name = args
    print(input_smiles, name, rxn_type, method, solvent_model, solvent_name)

In [13]:
something((**params))

TypeError: something() got an unexpected keyword argument 'input_smiles'

### read pickle

In [49]:
df = df_results.copy()
idx_ref = df.index[df['name'] == 'furan'][0]
# print(idx_ref)
# print(idx_ref[0])
print(df.at[idx_ref, 'lst_name_deprot'])

idx_deprot = ast.literal_eval(df.at[idx_ref, 'lst_name_deprot']).index('furan#-1=2')
print(idx_deprot)
print(ast.literal_eval(df.at[idx_ref, 'lst_E_rel'])[idx_deprot])

idx_ref = df.index[df['name'] == 'furan']


idx_ref = df.index[df['name'] == 'furan'][0]
idx_deprot = ast.literal_eval(df.at[idx_ref, 'lst_name_deprot']).index('furan#-1=2')
#take the negative as the relative energy is calculated as Furan --> Furan-
E_rel_ref = - ast.literal_eval(df.at[idx_ref, 'lst_E_rel'])[idx_deprot]

idx = 0
lst_E_rel = ast.literal_eval(df.at[idx, 'lst_E_rel'])
print(lst_E_rel)
pKa_ref = 35
temp = 298.15 #K 
gas_constant = 1.987 

lst_pKa = []
for E_rel in lst_E_rel:

    dG_exchange = E_rel_ref + E_rel
    pKa = pKa_ref + (dG_exchange/(gas_constant*temp*np.log(10)/1000))
    lst_pKa.append(pKa)

print(lst_pKa)

['furan#-1=2', 'furan#-1=3']

ValueError: malformed node or string: ['furan#-1=2', 'furan#-1=3']

In [50]:
def calc_pKa_v2(df, row_idx, pKa_ref=35, T=None):
    """
    Het-H + Furan- --> Het- + Furan
    """
    import ast
    if T == None:
        T = 298.15 #K
    
    gas_constant = 1.987 #kcal/(mol*K) or 8.31441 J/(mol*K) gas constant
    conversion_factor = Hartree * mol/kcal #convert energy from Hartree to kcal/mol

    idx_ref = df.index[df['name'] == 'furan'][0]
    # idx_deprot = ast.literal_eval(df.at[idx_ref, 'lst_name_deprot']).index('furan#-1=2')
    idx_deprot = df.at[idx_ref, 'lst_name_deprot'].index('furan#-1=2')
    #take the negative as the relative energy is calculated as Furan --> Furan-
    E_rel_ref = - df.at[idx_ref, 'lst_E_rel'][idx_deprot]

    # row_idx = 0
    lst_E_rel = df.at[row_idx, 'lst_E_rel']
    print(lst_E_rel)
    pKa_ref = 35
    temp = 298.15 #K 
    gas_constant = 1.987 

    lst_pKa = []
    for E_rel in lst_E_rel:
        dG_exchange = E_rel_ref + E_rel
        pKa = round(pKa_ref + (dG_exchange/(gas_constant*temp*np.log(10)/1000)), 1)
        lst_pKa.append(pKa)

    return lst_pKa

In [2]:
path_old = Path(Path.home()/'old_pKalculator'/'pKalculator'/'src'/'pKalculator'/'submitit_pKalculator_old4')

In [8]:
df_data = pd.read_pickle(path_old/'36395734_1_0_result.pkl')

In [9]:
df_data[1]

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa_deprot,lst_atomsite
1,thiophene,S1C=CC=C1,32.5,33.5,5a,-8675.292034,"[thiophene#-1=2, thiophene#-1=3]","[-8484.1649456893, -8479.065246324202]","[191.1270882297158, 196.22678759481278]",NaN,"[2, 3]"

df = pd.read_pickle('results.pkl')

In [3]:
def load_pickles(folder):
   return pd.concat([pd.read_pickle(pkl)[1].assign(file=pkl.name) 
            for pkl in folder.glob('*_result.pkl')
            ], ignore_index=True).sort_values(by='file')

In [6]:
df_results = load_pickles(path_old)

In [7]:
df_results

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa,lst_atomsite,gfn_method,solvent_model,solvent_name,file
0,furan,O1C=CC=C1,35.0,35.0,5a,-9193.62503,"[furan#-1=2, furan#-1=3]","[-8995.82790190762, -8986.317282436006]","[197.79712793161707, 207.30774740323068]",NaN,"[2, 3]",gfn 2,alpb,DMSO,36396456_0_0_result.pkl
1,thiophene,S1C=CC=C1,32.5,33.5,5a,-8675.292034,"[thiophene#-1=2, thiophene#-1=3]","[-8484.1649456893, -8479.065246324202]","[191.1270882297158, 196.22678759481278]",NaN,"[2, 3]",gfn 2,alpb,DMSO,36396456_1_0_result.pkl

In [8]:
for idx, row in df_results.iterrows():
    print(idx)
    lst_pKa = calc_pKa_v2(df=df_results, row_idx=idx, pKa_ref=35, T=None)
    df_results.at[idx, 'lst_pKa_deprot'] = lst_pKa

0

NameError: name 'calc_pKa_v2' is not defined

In [70]:
df_results

,name,smiles,pka_exp,pka_theor,ref,E_neutral,lst_name_deprot,lst_E,lst_E_rel,lst_pKa_deprot,lst_atomsite,file
0,furan,O1C=CC=C1,35.0,35.0,5a,-9193.62503,"[furan#-1=2, furan#-1=3]","[-8995.82790190762, -8986.317282436006]","[197.79712793161707, 207.30774740323068]","[35.0, 42.0]","[2, 3]",36395734_0_0_result.pkl
1,thiophene,S1C=CC=C1,32.5,33.5,5a,-8675.292034,"[thiophene#-1=2, thiophene#-1=3]","[-8484.1649456893, -8479.065246324202]","[191.1270882297158, 196.22678759481278]","[30.1, 33.8]","[2, 3]",36395734_1_0_result.pkl